apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: knawd-deployer-daemonset
  labels:
  {{ include "knawd-deployer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: knawd-deployer-ds
  template:
    metadata:
      labels:
        name: knawd-deployer-ds
    spec:
      restartPolicy: Always
      hostPID: true
      volumes:
        - name: node-root
          hostPath:
            path: /
        - name: entrypoint
          configMap:
            name: entrypoint
            defaultMode: 0744
      serviceAccountName: {{ include "knawd-deployer.serviceAccountName" . }}
      containers:
        - image: quay.io/knawd/deployer:{{ .Values.tag }}
          imagePullPolicy: Always
          name: deploy
          env:
            - name: VENDOR
              value: {{ include "knawd-deployer.calculated-vendor" . }}
            - name: LIB_LOCATION
              value: {{ include "knawd-deployer.libLocation" . }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: OCI_LOCATION
              value: {{ include "knawd-deployer.ociLocation" . }}
            - name: OCI_TYPE
              value: {{ .Values.ociType }}
            - name: NODE_ROOT
              value: {{ include "knawd-deployer.nodeRoot" . }}
            - name: IS_MICROK8S
              value: {{ include "knawd-deployer.isMicroK8s" . }}
            - name: AUTO_RESTART
              value: {{ .Values.autoRestart | quote }}
            - name: CONFIG_LOCATION
              value: {{ include "knawd-deployer.configLocation" . }}
            - name: LOOP
              value: "true"
            - name: PATCH_KNATIVE
              value: {{ .Values.patchKnative | quote }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: node-root
              mountPath: /mnt/node-root/
          command: ["/app/manager"]
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi