{{- if .Values.scc.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.scc.rolename }}
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: [{{ .Values.scc.name }}]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.scc.rolename }}
subjects:
  - kind: ServiceAccount
    name: {{ include "knawd-deployer.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ .Values.scc.rolename }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}