{{- if eq .Values.target "rhel8" }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  labels:
  {{ include "knawd-deployer.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "allows pod to run as root, privileged and run nsenter"
    "helm.sh/hook": pre-install
  name: {{ include "knawd-deployer.sccName" . }}
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: true
allowHostPorts: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
{{- end}}