
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knawd-deployer.serviceAccountName" . }}
  labels:
{{ include "knawd-deployer.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    kubernetes.io/description: "Service Account for RBAC definitions"
    "helm.sh/hook": pre-install
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}