name: Test wasmtime

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  wasmtime-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install wasmtime)
        run: ct install --config ct.yaml --helm-extra-set-args "--set target=ubuntu_18_04 --set ociType=crun-wasmtime"
